#!/usr/bin/env bash
# a script that displays "Best School" 10 times, but Hi for the 9th iteration.
i=1
while [[ $i -le 10 ]];
do
    if [[ $i -eq 9 ]];
    then
	echo "Hi"
    else
    	echo "Best School"
    fi
    (( i++ ))
done
