#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server
#with some specific requirements.

cp /etc/hosts new_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
echo "8.8.8.8 facebook.com" >> new_hosts
cp new_hosts /etc/hosts
